name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: artjomvolkov/action/send/mail@v3
        with:
          server_address: smtp.gmail.com
          server_post: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{github.repository}}
          body: ${{github.event.head_commit.message}}
          to: ${{github.event.pusher.name}}
          from: GitHub Actions
